### ISSUE TITLE
Does not seem to reorder imports

### ISSUE THREAD

**Issue by ndmckinley** [sbt/sbt-java-formatter#119]
Hi,

I'm seeing that this plugin does not reorder imports as required by the google java style guide 3.3.  For instance, if I make the following change to get the imports out of order

```diff
 import static play.test.Helpers.contentAsString;
 
 import akka.actor.ActorSystem;
-import controllers.AsyncController;
 import controllers.CountController;
+import controllers.AsyncController;
 import java.util.concurrent.CompletionStage;
 import org.junit.Test;
 import play.mvc.Result;
```

and run `sbt javafmtAll`, then `git diff`, I still see the diff (which is intentionally erroneous).

```diff
 import static play.test.Helpers.contentAsString;
 
 import akka.actor.ActorSystem;
-import controllers.AsyncController;
 import controllers.CountController;
+import controllers.AsyncController;
 import java.util.concurrent.CompletionStage;
 import org.junit.Test;
 import play.mvc.Result;
```

My plugins.sbt file contains `addSbtPlugin("com.lightbend.sbt" % "sbt-java-formatter" % "0.6.0")`.

**Comment by ennru** [comment]
This plugin relies on Google Java Formatter 1.7 which does not touch the order of imports.
 
You may be able of override it to a later version. See #102

**Comment by ndmckinley** [comment]
Got it - I decided to build my own solution which anyone who finds this issue later can see here:

https://github.com/seattle-uat/universal-application-tool/pull/27/files

See `bin/fmt` and `formatter.Dockerfile`.
