### ISSUE TITLE
Adapt to a world without Bintray

### ISSUE THREAD

**Issue by ennru** [sbt/sbt-java-formatter#126]

**Comment by JustinPihony** [comment]
@ennru See https://github.com/ktoso/sbt-jmh/commit/18ff4152a5c21badba8ec79ea148c73f08564008 for a reference. The code change itself is fairly trivial, however it needs an owner - ala https://issues.sonatype.org/browse/OSSRH-1324

Would that be you, @dwijnand or @ktoso - as the primary committers?
