### ISSUE TITLE
Non-snapshot release of this plugin

### ISSUE THREAD

**Issue by tomasherman** [sbt/sbt-java-formatter#134]
Hey guys,

would it be possible to release non-snapshot version of this plugin? At work we are not able to use snapshots :( and i struggle finding a non-snapshot version post-bintray.

Thanks!

**Comment by ennru** [comment]
@dwijnand can you have a look and publish it?

**Comment by dwijnand** [comment]
Done https://github.com/sbt/sbt-java-formatter/issues/138
