### ISSUE TITLE
Replace impl with Google`s google-java-format

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-java-formatter#19]
Current implementation of this plugin uses an eclipse library and XML file to setup and apply the formatting rules.

Instead, that impl could be replaced with Google's [google-java-format](https://github.com/google/google-java-format#as-a-library) which, despite not being configurable and enforce [Google Java Style](https://google.github.io/styleguide/javaguide.html) , seems to be maintained and integrates with IntelliJ and Eclipse alike.

/cc @raboof @timmoore

**Comment by ktoso** [comment]
Not configurable at all?

We specifically use 2 spaces in java docs in order to fit the snippets in similar amount of lines as scala, esp. in docs -- otherwise the more "functional" snippets become crazy nested.

**Comment by bantonsson** [comment]
@ktoso Google knows better you know...

**Comment by ktoso** [comment]
;-)

**Comment by ktoso** [comment]
Who am I to argue with the corporate overlords ;-)

Anything that works IMHO... currently we don't use this one in Akka but we should though

**Comment by raboof** [comment]
@ktoso incidentally the google style also indents blocks by 2 spaces ;)

**Comment by ktoso** [comment]
Yesssss!!!! No other requirements, do it! :D

**Comment by TimMoore** [comment]
@ignasi35 why clsoed?

**Comment by ktoso** [comment]
:-(
