### ISSUE TITLE
Add support for .editorconfig

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-java-formatter#22]
This sbt plugin could eventually support [`.editorconfig`](http://editorconfig.org/) or we could even discontinue this plugin in favour of a new, language-agnostic, `.editorconfig`-based one.

**Comment by bantonsson** [comment]
Maybe I'm missing something, but that just looks like a configuration file format specification, and does not have any "formatters". Are you planning on writing your own code formatters?

**Comment by renatocaval** [comment]
`.editorconfig` only allows some basic editor settings, like `Tab vs. Space`, `2sp vs. 4sp`, file encoding, line-breaking.

**Comment by bantonsson** [comment]
Yes, I figured that. I still fail to see how it's related to this plugin, unless you want to write your own formatters for this plugin that understands and reads the `.editorconfig` file and applies it to the formatting as well.

**Comment by ignasi35** [comment]
Thanks for the info @renatocaval. I thought `.editorconfig` was more powerful than that.

@bantonsson the general intention is to try to move away from eclipse-specific formats but  `.editorconfig` is not the way to go. I was not planning on writing custom formatters and rather reuse [existing libs](http://editorconfig.org/#create-a-plugin) like the current impl of this plugin uses eclipse's impl.

I think the opportunity is to have a separate plugin handling `.editorconfig` and keep this `.java` specific.
