### ISSUE TITLE
Fix credentials to bintray

### ISSUE THREAD

**Issue by 2m** [sbt/sbt-java-formatter#27]
@ktoso since this plugin is being released to your bintray repo (https://bintray.com/ktosopl/sbt-plugins/sbt-java-formatter) could you please update the credentials in .travis.yml file

https://github.com/sbt/sbt-java-formatter/blob/ff3ef38445ba729ca64f7432f52b4c417c0f938f/.travis.yml#L32-L37

to your Bintray username and API key from [here](https://bintray.com/profile/edit)?

This will enable automatic releases from Travis and I'll then be able to cut the `0.4.0` release.

**Comment by 2m** [comment]
The encrypted variables did not decrypt correctly: https://travis-ci.org/sbt/sbt-java-formatter/jobs/397186546

@ktoso can you try again, please?

**Comment by ktoso** [comment]
Hmm ok will perhaps ask you how to do it exactly... will be back at work soon (an hour or so). I guess I did something wrong

**Comment by ktoso** [comment]
Try now please I amended from right directory https://github.com/sbt/sbt-java-formatter/commit/9208d89a1c36e991b6dac21945fe616218784ff3

**Comment by 2m** [comment]
It works, thanks!
