### ISSUE TITLE
Unable to use version 0.5.0

### ISSUE THREAD

**Issue by mosaic-bharath-b** [sbt/sbt-java-formatter#62]
Unable to use version 0.5.0 but `sbt javafmt` works fine for 0.4.3

Error
`14:27 $ sbt javafmt
[info] Loading global plugins from /Users/bharath/.sbt/1.0/plugins
[info] Loading settings for project bank-account-validation-build from plugins.sbt ...
[info] Loading project definition from /Users/bharath/Documents/devel/monorepo/mosaic/services/bank-account-validation/project
[info] Loading settings for project bank-account-validation from build.sbt ...
[info] Set current project to bank-account-validation (in build file:/Users/bharath/Documents/devel/monorepo/mosaic/services/bank-account-validation/)
[error] java.lang.NoClassDefFoundError: Could not initialize class com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.trackSourcesViaCache(JavaFormatter.scala:135)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.cachedFormatSources(JavaFormatter.scala:109)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.apply(JavaFormatter.scala:36)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2(JavaFormatterPlugin.scala:69)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2$adapted(JavaFormatterPlugin.scala:63)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$.<init>(JavaFormatter.scala:67)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$.<clinit>(JavaFormatter.scala)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.trackSourcesViaCache(JavaFormatter.scala:135)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.cachedFormatSources(JavaFormatter.scala:109)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.apply(JavaFormatter.scala:36)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2(JavaFormatterPlugin.scala:69)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2$adapted(JavaFormatterPlugin.scala:63)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoClassDefFoundError: Could not initialize class com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.trackSourcesViaCache(JavaFormatter.scala:135)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.cachedFormatSources(JavaFormatter.scala:109)
[error]         at com.lightbend.sbt.javaformatter.JavaFormatter$.apply(JavaFormatter.scala:36)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2(JavaFormatterPlugin.scala:69)
[error]         at com.lightbend.sbt.JavaFormatterPlugin$.$anonfun$toBeScopedSettings$2$adapted(JavaFormatterPlugin.scala:63)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (bank-account-validation-api / Compile / javafmt) java.lang.NoClassDefFoundError: Could not initialize class com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$
[error] (bank-account-validation-impl / Compile / javafmt) java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error] (Compile / javafmt) java.lang.NoClassDefFoundError: Could not initialize class com.lightbend.sbt.javaformatter.JavaFormatter$Analysis$
[error] Total time: 0 s, completed 14 Jan, 2020 2:27:52 PM
`

**Comment by ennru** [comment]
Are you sure you are on sbt 1.3?

**Comment by mosaic-bharath-b** [comment]
> Are you sure you are on sbt 1.3?

Got it... my bad :)
